resource "aws_secretsmanager_secret" "tfer--ecsmoodlestackmoodledbSecre-s0pgWDdMMv8G" {
  description = "Generated by the CDK for stack: ecs-moodle-stack"
  name        = "ecsmoodlestackmoodledbSecre-s0pgWDdMMv8G"

  tags = {
    use = "terraformer"
  }

  tags_all = {
    use = "terraformer"
  }
}

resource "aws_secretsmanager_secret" "tfer--moodlepasswordsecret585482A-Tq2nCfOkm6Gw" {
  name = "moodlepasswordsecret585482A-Tq2nCfOkm6Gw"

  tags = {
    use = "terraformer"
  }

  tags_all = {
    use = "terraformer"
  }
}
